### PR TITLE
Add CDO-based regridding

### PR DESCRIPTION
**Pull request by ScottWales**

### CODE REVIEW

**Comment by ScottWales** [comment]
This is now feature complete

A sample notebook demonstrating the regridding is at https://github.com/coecms/coecms-util/blob/regrid-cdo/notebooks/regridding.ipynb

**Comment by ScottWales** [comment]
Thanks for the feedback @ccarouge, I've updated the comments

**Comment by ccarouge** [comment]
2 tests fail. Both because of an issue with 
`numpy.testing.assert_array_equal(cdo['var'].data[...], cms.data[...])`
within compare_regrids

` test/test_regrid.py:60: in compare_regrids
    numpy.testing.assert_array_equal(cdo['var'].data[...], cms.data[...])
/short/w35/ccc561/conda/envs/coecms/lib/python3.6/site-packages/dask/array/core.py:1302: in __array__
    x = self.compute()
/short/w35/ccc561/conda/envs/coecms/lib/python3.6/site-packages/dask/base.py:156: in compute
    (result,) = compute(self, traverse=False, **kwargs)
/short/w35/ccc561/conda/envs/coecms/lib/python3.6/site-packages/dask/base.py:395: in compute
    results = schedule(dsk, keys, **kwargs)
/short/w35/ccc561/conda/envs/coecms/lib/python3.6/site-packages/dask/threaded.py:75: in get
    pack_exception=pack_exception, **kwargs)
/short/w35/ccc561/conda/envs/coecms/lib/python3.6/site-packages/dask/local.py:501: in get_async
    raise_exception(exc, tb)
/short/w35/ccc561/conda/envs/coecms/lib/python3.6/site-packages/dask/compatibility.py:112: in reraise
    raise exc
/short/w35/ccc561/conda/envs/coecms/lib/python3.6/site-packages/dask/local.py:272: in execute_task
    result = _execute_task(task, data)
/short/w35/ccc561/conda/envs/coecms/lib/python3.6/site-packages/dask/local.py:252: in _execute_task
    args2 = [_execute_task(a, cache) for a in args]
/short/w35/ccc561/conda/envs/coecms/lib/python3.6/site-packages/dask/local.py:252: in <listcomp>
    args2 = [_execute_task(a, cache) for a in args]
/short/w35/ccc561/conda/envs/coecms/lib/python3.6/site-packages/dask/local.py:252: in _execute_task
    args2 = [_execute_task(a, cache) for a in args]
/short/w35/ccc561/conda/envs/coecms/lib/python3.6/site-packages/dask/local.py:252: in <listcomp>
    args2 = [_execute_task(a, cache) for a in args]
/short/w35/ccc561/conda/envs/coecms/lib/python3.6/site-packages/dask/local.py:249: in _execute_task
    return [_execute_task(a, cache) for a in arg]
/short/w35/ccc561/conda/envs/coecms/lib/python3.6/site-packages/dask/local.py:249: in <listcomp>
    return [_execute_task(a, cache) for a in arg]
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

arg = (<built-in function matmul>, (<function concatenate_axes at 0x7faaa0272048>, [('array-04ca34526f888b8dbe268d218481f4a2...7c80>, 'array-original-cb8d6f97b684decbf8acc37a3c30a754', (slice(0, 4, None), slice(0, 4, None)), False, False)], [0]))
cache = {'array-original-cb8d6f97b684decbf8acc37a3c30a754': <COO: shape=(4, 4), dtype=float64, nnz=16, fill_value=0.0>, ('array-04ca34526f888b8dbe268d218481f4a2', 0, 0): array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])}
dsk = None

        if isinstance(arg, list):
            return [_execute_task(a, cache) for a in arg]
        elif istask(arg):
            func, args = arg[0], arg[1:]
            args2 = [_execute_task(a, cache) for a in args]
>           return func(*args2)
E           TypeError: __array__() takes 1 positional argument but 2 were given`

**Comment by ScottWales** [comment]
Fixed for the moment by converting the sparse weight matrix to a dense array. might not be the greatest for large grids

**Comment by ccarouge** [comment]
tests are working for me now. Looking at the notebook example.

**Comment by ccarouge** [comment]
Some bits of the notebook aren't clear to me. In "Target grid", you say: 

> The Regridder object feeds this information into CDO to generate the weights - this may not be a good idea for really big grids!

Then you say in "Regridding":

> The Regridder will generate and save the regridding weights, so the same weights can be re-used multiple times. Call Regridder.regrid() to apply the weights to a dataset.
> 
> This is Dask aware, so should work fine for large datasets

So for large datasets, it's good to have the weights saved in Regridder, but it's not good to calculate them via a straight call to _Regridder()_. So what are we suppose to do for large datasets? Calculate the weights independently (for example with ESMF), store in file and give this file as input when regridding? Maybe add a section at the end on a recommended or typical workflow for large grid. And we need to define what large means :)

**Comment by ScottWales** [comment]
Thanks Claire. I've updated the notebook to hopefully make things clearer, but if not here's a high level breakdown.

The possible slow-down I'm warning about is from CDO generating the regridding weights, particularly for say quarter degree ocean grids where even ESMF needs a few MPI ranks to do the calculation.

The next cell is talking about doing the actual regridding operation, once you have the weights. This is a dask-aware matrix multiplication, so should be able to handle say a dataset with a large amount of timesteps/levels fine.

**Comment by ScottWales** [comment]
Thanks Claire

**Pull request merged**
